language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
global:
  - PACKAGE=ocplib-endian
  - TESTS=true
env:
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.03
os:
  - linux
  - osx
