name: Make Apk CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Build-Apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Cache debug certificate
      uses: actions/cache@v2
      with:
        path: _build/debug.keystore
        key: debug-keystore
    - name: Restore debug keystore from github Secrets 
      run: |
        mkdir -p _build
        cd "_build"
        # Check if exist and use the secret named DEBUG_KEYSTORE
        # The contents of the secret can be obtained -
        #    from the debug.keystore.asc from you local _build folder
        if [[ ! "${{ secrets.DEBUG_KEYSTORE }}" = "" ]]; then
            echo "${{ secrets.DEBUG_KEYSTORE }}" > "debug.keystore.asc"
            if [[ -s "debug.keystore.asc" ]]; then
                gpg -d --passphrase "debug0" --batch "debug.keystore.asc" > "debug.keystore"
            fi
        fi
    - name: Build
      run: make
    - name: Save debug apk
      uses: actions/upload-artifact@v2
      with:
        name: "${{github.repository_owner}} ${{github.ref_name}} debug_apk"
        path: _build/*.apk
